use_frameworks!

platform :ios, '13.0'

target 'AppReviewKit_Example' do
  pod 'AppReviewKit', :path => '../'
  pod 'SnapKit', '~> 5.0'

  target 'AppReviewKit_Tests' do
    inherit! :search_paths

    
  end
end
